### PR TITLE
Replay Layout Mode

### PR DESCRIPTION
**Pull request by pkbullock**
New Feature: Replay Page Layout Mode, how this works:

* Run transformation with IsReplayCapture - this creates a reference to the page page in memory
* User moves web parts around in SharePoint UI for capture page - sections created/emphasis preserved
* Run subsequent transform with "IsReplayLayout" and pages transformed will apply to the layout changes made by the user in the UI, to subsequent transform pages. 
* You can still specify the page layout mapping, rows/columns are ignored. The rest is as per normal.
* By design, this only works for source pages that have the SAME source page layout

Current features are limited to **PublishingPages** only.

I have unit tests BUT some have heavy coupling to my setup - which isn't the best approach. 
There is lots more testing to be done and think this should be preview when released as my rig just doesn't have the scenarios a real transformation project would have.

I will shortly be submitted the PnP PowerShell PR for the cmdlet changes.
Any questions just shout, happy to do a demo and receive feedback of course :-)

Reference issue #369

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi @pkbullock , thanks for the work on this one!

I think this requires a quick meeting for me to better understand how it works. Can you send me a mail with your availability for next week so we can setup a Teams call?

**Comment by pkbullock** [comment]
Pinged on email, in the meantime, I will do more testing.

**Comment by pkbullock** [comment]
I've converted this to draft until we both feel its ready for merging. I haven't yet progressed this since our last call.

**Comment by jansenbe** [comment]
Hey @pkbullock , I'm closing this PR for now. I don't think there's demand for this and to make it really valuable for a broader audience there's still a ton of work

**Pull request closed without merging**
